<<<<<<< HEAD
# Generated by Django 4.2.3 on 2023-11-04 16:00
=======
# Generated by Django 4.2.3 on 2023-11-05 12:38
>>>>>>> c21bb4f

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('tours', '0002_alter_address_options_alter_city_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tours', '0001_initial'),
>>>>>>> c21bb4f
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('body', models.TextField(default=None, max_length=5000, verbose_name='Текст отзыва')),
                ('created', models.DateTimeField(default=datetime.datetime(2023, 11, 4, 22, 0, 47, 713006), verbose_name='Создан')),
                ('updated', models.DateTimeField(default=datetime.datetime(2023, 11, 4, 22, 0, 47, 713006), verbose_name='Изменен')),
=======
                ('body', models.TextField(default=None, max_length=5000, verbose_name='Сообщение')),
                ('created', models.DateTimeField(default=datetime.datetime(2023, 11, 5, 18, 38, 51, 332513))),
                ('updated', models.DateTimeField(default=datetime.datetime(2023, 11, 5, 18, 38, 51, 332513))),
>>>>>>> c21bb4f
                ('active', models.BooleanField(default=True)),
                ('name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='имя', to=settings.AUTH_USER_MODEL)),
                ('tours', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tours.tour')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ('created',),
            },
        ),
    ]
