# Generated by Django 4.2.3 on 2023-11-04 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 4, 22, 2, 3, 482795), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 4, 22, 2, 3, 482795), verbose_name='Изменен'),
        ),
    ]
