<<<<<<< HEAD
# Generated by Django 4.2.3 on 2023-11-04 16:02
=======
# Generated by Django 4.2.3 on 2023-11-05 12:39
>>>>>>> c21bb4f

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created',
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 4, 22, 2, 3, 482795), verbose_name='Создан'),
=======
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 5, 18, 39, 0, 661128)),
>>>>>>> c21bb4f
        ),
        migrations.AlterField(
            model_name='review',
            name='updated',
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 4, 22, 2, 3, 482795), verbose_name='Изменен'),
=======
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 5, 18, 39, 0, 661128)),
>>>>>>> c21bb4f
        ),
    ]
