# Generated by Django 4.2.3 on 2023-11-06 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0017_alter_review_created_alter_review_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='tours',
            new_name='tours_id',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='name',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.TextField(default=None, max_length=5000, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 6, 13, 11, 58, 488487)),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 6, 13, 11, 58, 488487)),
        ),
    ]
