# Generated by Django 4.2.3 on 2023-11-06 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0018_rename_tours_review_tours_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 6, 13, 12, 22, 222076)),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 6, 13, 12, 22, 222076)),
        ),
    ]
